# This is a basic workflow to help you get started with Actions

name: GitHub Actions Test

on: [push]

jobs:
  test:
    name: Warizan Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: python warizan_test.py
